import { Toaster } from '@/components/ui/toaster'
import AuthContextProvider from '@/contexts/AuthContext'
import { WalletAdapterProvider } from '@/contexts/WalletProvider'
import type { Metadata } from 'next'
import { Inter, Martel, Montaga, Monoton, Montserrat } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const mat = Montserrat({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={mat.className}>
        <WalletAdapterProvider>
          <AuthContextProvider>
            <Toaster />
            {children}
          </AuthContextProvider>
        </WalletAdapterProvider>
      </body>
    </html>
  )
}
